name = "NonstationaryProcesses"
uuid = "7656fb31-40ed-4019-8ece-32bdcc5fce69"
authors = ["brendanjohnharris <brendanjohnharris@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DynamicalSystems = "61744808-ddfa-5f27-97ff-6e42cc95d634"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
<<<<<<< HEAD
DynamicalSystems = "1.7"
Plots = "1.10"
=======
Revise = "3.1"
>>>>>>> origin/compathelper/new_version/2021-02-19-00-41-29-035-3438069830
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
